### ISSUE TITLE
Is serde ever used here?

### ISSUE THREAD

**Issue by TheTechRobo** [rhapsodyn/rust-json-foo#2]
I see it in some commented-out code, but I'm not sure if that code is WIP or removed.

In the latter case, serde should be removed from the Cargo.toml to reduce the amount of dependencies

**Comment by rhapsodyn** [comment]
Oh, this project is some kinda to-learn-rust one.

Since someone else is reading, I'd refac it more seriously. 

See [d7748d015d8a34479ed1db90936cb440223d287c](https://github.com/rhapsodyn/rust-json-foo/commit/d7748d015d8a34479ed1db90936cb440223d287c)

**Comment by TheTechRobo** [comment]
Yeah, this should hopefully help me figure out how to parse things in Rust.

I've always thought lexers were magic, lol.
