### ISSUE TITLE
Code style question: Should `True` and `False` in the enum be merged into `Bool(bool)`?

### ISSUE THREAD

**Issue by TheTechRobo** [rhapsodyn/rust-json-foo#3]
The other types are generic types such as Object and Array because they obviously have to be.

Should `True` and `False` be merged into `Bool(bool)` to match those other generic types?

This is a code style question and I'm fine with any answer.

**Comment by rhapsodyn** [comment]
Separating `True` and `False` seems simple (less nested `match`) and intuitive ([here](https://github.com/serde-rs/json/blob/master/src/de.rs#L278) and [there](https://github.com/v8/v8/blob/master/src/json/json-parser.cc#L37))

**Comment by TheTechRobo** [comment]
Good point, I didn't think about the nested `match`es.
